import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-full w-full flex-col items-center justify-center bg-white">
        {children}
      </body>
    </html>
  );
}
