# Farmer

# Registeration

POST http://localhost:5000/farmer/register HTTP/1.1
Content-Type: application/json

{
    "adharNo" : "123456789012",
    "fullName": "Rajesh",
    "phoneNo": "1234567890",
    "email": "temp@gmail.com",
    "address": "Bangalore",
    "username": "Rajesh",
    "password": "Bangalore",
    "landSize": "10",
    "typeOfCrop":["Rice","Wheat","Maize"]
}

###

#login

POST http://localhost:5000/farmer/login HTTP/1.1
Content-Type: application/json

{
    "username": "Rajesh",
    "password": "Bangalore"
}


###

# update

PUT http://localhost:5000/farmer/update/65586eb95a4f35d460e56b17 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTg2ZWI5NWE0ZjM1ZDQ2MGU1NmIxNyIsInVzZXJuYW1lIjoiUmFqZXNoIiwiaWF0IjoxNzAwMjk0MzI5fQ.F_01JSrGwMCiDzb8zYbIN_WAWBMP5WxDj3IXxus0eHI

{
    "adharNo" : "2121212121",
    "fullName": "Rajesh",
    "phoneNo": "1234567890",
    "email": "temp@gmail.com",
    "address": "Bangalore",
    "username": "Rajesh",
    "password": "Bangalore",
    "landSize": "10",
    "typeOfCrop":["Rice","Wheat","Maize"]
}
