# Farmer

# Registeration

POST http://localhost:5000/farmer/register HTTP/1.1
Content-Type: application/json

{
    "adharNo" : "123456789012",
    "fullName": "Rajesh",
    "phoneNo": "1234567890",
    "email": "temp@gmail.com",
    "address": "Bangalore",
    "username": "Rajesh",
    "password": "Bangalore",
    "landSize": "10",
    "typeOfCrop":["Rice","Wheat","Maize"]
}

###

#login

POST http://localhost:5000/farmer/login HTTP/1.1
Content-Type: application/json

{
    "username": "Rajesh",
    "password": "Bangalore"
}


###

# update


